server:
  port: 8091

spring:
  application:
    name: customers

  datasource:
    url: jdbc:mysql://localhost:3306/customers
    driverClassName: com.mysql.cj.jdbc.Driver
    username: spring
    password: SuperSafeUserPassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  docker:
    compose:
      enabled: true
      file: ./customers/docker-compose.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
