server:
  port: 8090

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

cloud:
  gateway:
    discovery:
      locator:
        enabled: true