services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: loan_proposals
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: SuperSafeUserPassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: SuperSafeAdminPassword
      PGADMIN_LISTEN_PORT: 15432
    ports:
      - "15432:15432"
    depends_on:
      - postgres
  loan-proposals:
    build:
      context: ../
      dockerfile: loan-proposals/Dockerfile.prod
    image: spring-containers-loan-proposals:stable
    ports:
      - "8093:8093"
    depends_on:
      - postgres