server:
  port: 8093

spring:
  application:
    name: loan-proposals

  datasource:
    url: jdbc:postgresql://localhost:5432/loan_proposals
    driverClassName: org.postgresql.Driver
    username: spring
    password: SuperSafeUserPassword

  docker:
    compose:
      enabled: true
      file: ./loan-proposals/docker-compose.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

endpoints:
  risk-analysis-microservice:
    baseUrl: http://localhost:8092/risk-analysis/current-effort-rate

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/