server:
  port: 8092
  servlet:
    context-path: /risk-analysis

spring:
  application:
    name: risk-analysis

endpoints:
  customers-microservice:
    baseUrl: http://localhost:8091/customers

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/