server:
  port: 8092
  servlet:
    context-path: /risk-analysis

spring:
  application:
    name: risk-analysis

endpoints:
  customers-microservice:
    baseUrl: http://host.docker.internal:8091/customers

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/